# Generated by Django 4.0.6 on 2022-08-07 05:23

import apps.properties.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificaión')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.SlugField(max_length=150, verbose_name='Titulo')),
                ('sub_property_type', models.CharField(choices=[('ca', 'Casa'), ('pi', 'Pieza'), ('ch', 'Conjunto Habitacional'), ('co', 'Condominio'), ('bu', 'Bungalow')], max_length=2, verbose_name='Subtipo de propiedad')),
                ('builded_surface', models.PositiveIntegerField(verbose_name='Superficie construida (m²)')),
                ('land_surface', models.PositiveIntegerField(verbose_name='Superficie terreno (m²)')),
                ('num_rooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Dormitorios')),
                ('num_bathrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Baños')),
                ('floor_type', models.CharField(max_length=150, verbose_name='Tipo piso')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Esta propiedad está amoblada')),
                ('sub_rent_type', models.CharField(blank=True, choices=[('am', 'Arriendo Mensual'), ('as', 'Arriendo Semanal'), ('ad', 'Arriendo Diario')], max_length=2, verbose_name='Subtipo de renta')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.properties.models.house_directory_path, verbose_name='Imagen')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('publish_type', models.CharField(choices=[('ve', 'Venta'), ('ar', 'Arriendo'), ('at', 'Arriendo Temporada')], max_length=2, verbose_name='Tipo de Operación')),
                ('type_price', models.CharField(choices=[('uf', 'UF'), ('clp', '$')], max_length=3, verbose_name='Tipo Precio')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificaión')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('property_type', models.CharField(choices=[('de', 'Departamento'), ('ca', 'Casa'), ('of', 'Oficina'), ('lc', 'Local Comercial'), ('te', 'Terreno'), ('pa', 'Parcela'), ('ag', 'Agrícola'), ('in', 'Industrial'), ('bo', 'Bodega'), ('es', 'Estacionamiento'), ('va', 'Vacacional')], max_length=2, verbose_name='Tipo de Propiedad')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('commune', models.CharField(max_length=50, verbose_name='Comuna')),
                ('street_address', models.CharField(max_length=50, verbose_name='Calle')),
                ('street_number', models.CharField(max_length=50, verbose_name='Número')),
                ('house_number', models.CharField(blank=True, max_length=50, verbose_name='Número depto/casa (Opcional)')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificaión')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('image', models.ImageField(upload_to=apps.properties.models.house_images_directory_path)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='properties.house')),
            ],
            options={
                'verbose_name': 'HouseImage',
                'verbose_name_plural': 'HouseImages',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='properties.location', verbose_name='Locación'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificaión')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.SlugField(max_length=150, verbose_name='Titulo')),
                ('sub_property_type', models.CharField(choices=[('de', 'Departamento'), ('lo', 'Loft'), ('du', 'Dúplex'), ('co', 'Condominio')], max_length=2, verbose_name='Subtipo de propiedad')),
                ('builded_surface', models.PositiveIntegerField(verbose_name='Superficie construida (m²)')),
                ('land_surface', models.PositiveIntegerField(verbose_name='Superficie terreno (m²)')),
                ('num_rooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Dormitorios')),
                ('num_bathrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Baños')),
                ('common_expenses', models.PositiveIntegerField(verbose_name='Gasos comunes')),
                ('floor_type', models.CharField(max_length=150, verbose_name='Tipo piso')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Esta propiedad está amoblada')),
                ('sub_rent_type', models.CharField(blank=True, choices=[('am', 'Arriendo Mensual'), ('as', 'Arriendo Semanal'), ('ad', 'Arriendo Diario')], max_length=2, verbose_name='Subtipo de renta')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.properties.models.house_directory_path, verbose_name='Imagen')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('publish_type', models.CharField(choices=[('ve', 'Venta'), ('ar', 'Arriendo'), ('at', 'Arriendo Temporada')], max_length=2, verbose_name='Tipo de Operación')),
                ('type_price', models.CharField(choices=[('uf', 'UF'), ('clp', '$')], max_length=3, verbose_name='Tipo Precio')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='properties.location', verbose_name='Locación')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
            },
        ),
    ]
