# Generated by Django 4.1.1 on 2023-01-01 21:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="distribution",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Baño Visita", "Baño Visita"),
                    ("Hall", "Hall"),
                    ("Antejardin", "Antejardin"),
                    ("Patio de Servicio", "Patio de Servicio"),
                    ("Estar de Servicio", "Estar de Servicio"),
                    ("Jardin", "Jardin"),
                    ("Despensa", "Despensa"),
                    ("Sala Estar", "Sala Estar"),
                    ("Quincho", "Quincho"),
                    ("Lavadero Interior", "Lavadero Interior"),
                    ("Lavadero Exterior", "Lavadero Exterior"),
                    ("Escritorio", "Escritorio"),
                    ("Mansarda", "Mansarda"),
                    ("Terraza", "Terraza"),
                ],
                default="",
                max_length=250,
                verbose_name="Espacios Adicionales",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Comedor Diario", "Comedor Diario"),
                    ("Cocina Equipada", "Cocina Equipada"),
                    ("Cocina Amoblada", "Cocina Amoblada"),
                ],
                default="",
                max_length=250,
                verbose_name="Cocina",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="other",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Persianas", "Persianas"),
                    ("Protecciones Ventana", "Protecciones Ventana"),
                    ("Termopaneles", "Termopaneles"),
                    ("Jacuzzi", "Jacuzzi"),
                    ("Piscina", "Piscina"),
                ],
                default="",
                max_length=250,
                verbose_name="Otros",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="service",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Internet", "Internet"),
                    ("Luz", "Luz"),
                    ("Agua Potable", "Agua Potable"),
                    ("Alcantarillado", "Alcantarillado"),
                    ("Alarma", "Alarma"),
                    ("Telefono", "Telefono"),
                    ("Riego Automatico", "Riego Automatico"),
                    ("Porton Automatico", "Porton Automatico"),
                    ("TV Cable", "TV Cable"),
                    ("Chimenea", "Chimenea"),
                    ("Calefaccion", "Calefaccion"),
                    ("Aire Acondicionado", "Aire Acondicionado"),
                ],
                default="",
                max_length=250,
                verbose_name="Servicios",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="distribution",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Baño Visita", "Baño Visita"),
                    ("Hall", "Hall"),
                    ("Antejardin", "Antejardin"),
                    ("Patio de Servicio", "Patio de Servicio"),
                    ("Estar de Servicio", "Estar de Servicio"),
                    ("Jardin", "Jardin"),
                    ("Despensa", "Despensa"),
                    ("Sala Estar", "Sala Estar"),
                    ("Quincho", "Quincho"),
                    ("Lavadero Interior", "Lavadero Interior"),
                    ("Lavadero Exterior", "Lavadero Exterior"),
                    ("Escritorio", "Escritorio"),
                    ("Mansarda", "Mansarda"),
                    ("Terraza", "Terraza"),
                ],
                default="",
                max_length=250,
                verbose_name="Espacios Adicionales",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Comedor Diario", "Comedor Diario"),
                    ("Cocina Equipada", "Cocina Equipada"),
                    ("Cocina Amoblada", "Cocina Amoblada"),
                ],
                default="",
                max_length=250,
                verbose_name="Cocina",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="other",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Persianas", "Persianas"),
                    ("Protecciones Ventana", "Protecciones Ventana"),
                    ("Termopaneles", "Termopaneles"),
                    ("Jacuzzi", "Jacuzzi"),
                    ("Piscina", "Piscina"),
                ],
                default="",
                max_length=250,
                verbose_name="Otros",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="service",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Internet", "Internet"),
                    ("Luz", "Luz"),
                    ("Agua Potable", "Agua Potable"),
                    ("Alcantarillado", "Alcantarillado"),
                    ("Alarma", "Alarma"),
                    ("Telefono", "Telefono"),
                    ("Riego Automatico", "Riego Automatico"),
                    ("Porton Automatico", "Porton Automatico"),
                    ("TV Cable", "TV Cable"),
                    ("Chimenea", "Chimenea"),
                    ("Calefaccion", "Calefaccion"),
                    ("Aire Acondicionado", "Aire Acondicionado"),
                ],
                default="",
                max_length=250,
                verbose_name="Servicios",
            ),
        ),
    ]
