# Generated by Django 4.1.1 on 2022-12-13 01:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Comedor Diario", "Comedor Diario"),
                    ("Cocina Equipada", "Cocina Equipada"),
                    ("Cocina Amoblada", "Cocina Amoblada"),
                ],
                default="",
                max_length=50,
                verbose_name="Cocina",
            ),
        ),
    ]
