# Generated by Django 4.1.1 on 2022-10-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="google_url",
            field=models.URLField(blank=True, null=True, verbose_name="Google Maps"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Destacada?"),
        ),
        migrations.AddField(
            model_name="property",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="Video"),
        ),
    ]
