# Generated by Django 4.0.6 on 2022-08-08 03:04

import apps.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_apartmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='num_parkings',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1, max_length=2, verbose_name='Estacionamiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.properties.models.apartment_directory_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to=apps.properties.models.apartment_images_directory_path),
        ),
        migrations.AlterField(
            model_name='house',
            name='thumbnail',
            field=models.ImageField(blank=True, default=1, upload_to=apps.properties.models.house_directory_path, verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
