# Generated by Django 4.1.1 on 2022-12-13 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_house_kitchen"),
    ]

    operations = [
        migrations.RemoveField(model_name="house", name="floor_type",),
    ]
