# Generated by Django 4.1.1 on 2022-12-13 20:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_remove_house_floor_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="common_expenses",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Gastos comunes*"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="distribution",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Baño Visita", "Baño Visita"),
                    ("Hall", "Hall"),
                    ("Antejardin", "Antejardin"),
                    ("Patio de Servicio", "Patio de Servicio"),
                    ("Estar de Servicio", "Estar de Servicio"),
                    ("Jardin", "Jardin"),
                    ("Despensa", "Despensa"),
                    ("Sala Estar", "Sala Estar"),
                    ("Quincho", "Quincho"),
                    ("Lavadero Interior", "Lavadero Interior"),
                    ("Lavadero Exterior", "Lavadero Exterior"),
                    ("Escritorio", "Escritorio"),
                    ("Mansarda", "Mansarda"),
                    ("Terraza", "Terraza"),
                ],
                default="",
                max_length=250,
                verbose_name="Distribución",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="kitchen",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Comedor Diario", "Comedor Diario"),
                    ("Cocina Equipada", "Cocina Equipada"),
                    ("Cocina Amoblada", "Cocina Amoblada"),
                ],
                default="",
                max_length=250,
                verbose_name="Cocina",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="other",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Persianas", "Persianas"),
                    ("Protecciones Ventana", "Protecciones Ventana"),
                    ("Termopaneles", "Termopaneles"),
                ],
                default="",
                max_length=250,
                verbose_name="Otros",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="service",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Alarma", "Alarma"),
                    ("Jacuzzi", "Jacuzzi"),
                    ("Telefono", "Telefono"),
                    ("Riego Automatico", "Riego Automatico"),
                    ("Porton Automatico", "Porton Automatico"),
                    ("Piscina", "Piscina"),
                    ("TV Cable", "TV Cable"),
                    ("Chimenea", "Chimenea"),
                    ("Calefaccion", "Calefaccion"),
                    ("Aire Acondicionado", "Aire Acondicionado"),
                ],
                default="",
                max_length=250,
                verbose_name="Servicios",
            ),
        ),
    ]
