# Generated by Django 4.1.1 on 2023-01-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_is_commission_paid"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="is_commission_paid",),
        migrations.CreateModel(
            name="PropertyManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="tipo")),
                ("total", models.IntegerField()),
                (
                    "commission_percentage",
                    models.PositiveIntegerField(
                        verbose_name="Porcentaje Comisión(Valor Entero)"
                    ),
                ),
                ("commission_price", models.IntegerField()),
                (
                    "is_commission_paid",
                    models.BooleanField(default=False, verbose_name="Comisión Pagada"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managers",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "PropertyManager",
                "verbose_name_plural": "PropertyManagers",
            },
        ),
    ]
