# Generated by Django 4.1.1 on 2022-10-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_latitude_property_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre Completo"),
                ),
                ("from_email", models.EmailField(max_length=50, verbose_name="Email")),
                ("subject", models.CharField(max_length=2, verbose_name="Asunto")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="Télefono(opcional)"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensaje")),
            ],
            options={
                "verbose_name": "PropertyContact",
                "verbose_name_plural": "PropertyContacts",
            },
        ),
    ]
