# Generated by Django 4.0.6 on 2022-08-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_house_num_parkings_alter_apartment_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='builded_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Construcción'),
        ),
        migrations.AddField(
            model_name='house',
            name='num_cellars',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Bodegas'),
        ),
        migrations.AddField(
            model_name='house',
            name='num_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pisos'),
        ),
        migrations.AddField(
            model_name='house',
            name='orientation',
            field=models.CharField(blank=True, choices=[('n', 'Norte'), ('s', 'Sur'), ('o', 'Oriente'), ('p', 'Poniente'), ('ns', 'Norte - Sur'), ('no', 'Nor - Oriente'), ('np', 'Nor - Poniente'), ('so', 'Sur - Oriente'), ('sp', 'Sur - Poniente'), ('op', 'Oriente - Poniente'), ('nso', 'Norte - Sur - Oriente'), ('nsp', 'Norte - Sur - Poniente'), ('nop', 'Norte - Oriente - Poniente'), ('sop', 'Sur - Oriente - Poniente'), ('all', 'Todas')], max_length=3, verbose_name='Orientación'),
        ),
        migrations.AddField(
            model_name='house',
            name='service',
            field=models.CharField(blank=True, choices=[('s', 'Si'), ('n', 'No')], max_length=1, verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='house',
            name='num_parkings',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Estacionamientos'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titulo'),
        ),
    ]
