# Generated by Django 4.1.1 on 2023-01-05 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_remove_property_is_commission_paid_propertymanager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertymanager",
            old_name="commission_price",
            new_name="commission_value",
        ),
        migrations.RenameField(
            model_name="propertymanager", old_name="total", new_name="price",
        ),
        migrations.RenameField(
            model_name="propertymanager", old_name="type", new_name="type_property",
        ),
        migrations.AddField(
            model_name="propertymanager",
            name="type_price",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=50,
                verbose_name="tipo de precio",
            ),
            preserve_default=False,
        ),
    ]
