# Generated by Django 4.1.1 on 2022-12-14 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_remove_apartment_floor_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Realtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Apellido"),
                ),
                (
                    "phone1",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="Telefono 1"
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="Telefono 2"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, null=True, verbose_name="Correo"
                    ),
                ),
            ],
            options={"verbose_name": "Realtor", "verbose_name_plural": "Realtors",},
        ),
        migrations.RemoveField(model_name="property", name="email",),
        migrations.RemoveField(model_name="property", name="phone1",),
        migrations.RemoveField(model_name="property", name="phone2",),
        migrations.AddField(
            model_name="property",
            name="realtor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.realtor",
            ),
        ),
    ]
