# Generated by Django 4.1.1 on 2022-12-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_remove_propertycontact_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="google_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Google Maps"
            ),
        ),
    ]
