# Generated by Django 4.1.1 on 2023-01-05 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_remove_propertymanager_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymanager",
            name="type_property",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                verbose_name="Tipo de Propiedad",
            ),
            preserve_default=False,
        ),
    ]
