# Generated by Django 4.1.1 on 2023-01-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_propertymanager_type_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property", name="slug", field=models.SlugField(unique=True),
        ),
    ]
