# Generated by Django 4.1.1 on 2022-12-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_alter_property_google_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="google_url",
            field=models.TextField(blank=True, null=True, verbose_name="Google Maps"),
        ),
    ]
