# Generated by Django 4.1.1 on 2022-12-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_alter_property_realtor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="builded_surface",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Superficie construida (m²)"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="builded_year",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Año de Construcción"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="common_expenses",
            field=models.PositiveIntegerField(default=0, verbose_name="Gastos comunes"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="num_apartment",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número Depto"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="num_bathrooms",
            field=models.PositiveIntegerField(default=0, verbose_name="Baños"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="num_cellars",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Bodegas"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="num_floors",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Pisos"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="num_parkings",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Estacionamientos"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="num_rooms",
            field=models.PositiveIntegerField(default=0, verbose_name="Dormitorios"),
        ),
        migrations.AlterField(
            model_name="property",
            name="commune",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.commune",
                verbose_name="Comuna",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.region",
                verbose_name="Región",
            ),
        ),
    ]
