# Generated by Django 4.1.1 on 2022-12-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre Completo"),
                ),
                ("from_email", models.EmailField(max_length=50, verbose_name="Email")),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("a1", "Asunto 1"),
                            ("a2", "Asunto 2"),
                            ("a3", "Asunto 3"),
                            ("a4", "Asunto 4"),
                            ("a5", "Asunto 5"),
                        ],
                        max_length=2,
                        verbose_name="Asunto",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="Télefono(opcional)"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensaje")),
            ],
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts",},
        ),
        migrations.CreateModel(
            name="OwnerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre Completo"),
                ),
                ("from_email", models.EmailField(max_length=50, verbose_name="Email")),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("", "Seleccione un tipo"),
                            ("Venta", "Venta"),
                            ("Arriendo", "Arriendo"),
                            ("Arriendo Temporada", "Arriendo Temporada"),
                            ("Permuta", "Permuta"),
                        ],
                        max_length=50,
                        verbose_name="Asunto",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="Télefono(opcional)"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensaje")),
            ],
            options={
                "verbose_name": "OwnerContact",
                "verbose_name_plural": "OwnerContacts",
            },
        ),
    ]
