# Generated by Django 4.1.1 on 2022-12-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownercontact",
            name="subject",
            field=models.CharField(
                choices=[
                    ("", "Seleccione un tipo"),
                    ("Venta", "Venta"),
                    ("Arriendo", "Arriendo"),
                    ("Arriendo Temporada", "Arriendo Temporada"),
                    ("Permuta", "Permuta"),
                ],
                max_length=50,
                verbose_name="Asunto",
            ),
        ),
    ]
