# Generated by Django 4.1.1 on 2022-10-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(
                choices=[
                    ("a1", "Asunto 1"),
                    ("a2", "Asunto 2"),
                    ("a3", "Asunto 3"),
                    ("a4", "Asunto 4"),
                    ("a5", "Asunto 5"),
                ],
                max_length=2,
                verbose_name="Asunto",
            ),
        ),
    ]
