# Generated by Django 4.1.1 on 2022-11-02 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_ownercontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownercontact",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de Creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ownercontact",
            name="modified",
            field=models.DateField(auto_now=True, verbose_name="Fecha de Modificaión"),
        ),
        migrations.AddField(
            model_name="ownercontact",
            name="state",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
    ]
